name: docker build test

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --debug
    - name: Build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: dr-viewer:${{ GITHUB_HEAD_REF }}
        build-args: |
            "REACT_APP_FAIROSHOST=https://fairos.dev.fairdatasociety.org/
            "REACT_APP_FAIRDRIVEHOST=https://app.fairdrive.dev.fairdatasociety.org"
            "DNS_ADDRESS=app.fairdrive.dev.fairdatasociety.org"
